## 2. Reading the Data

In [16]:
%matplotlib inline

#importing our necessary libraries
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
import seaborn as sns; sns.set(font_scale=1.2)
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

In [17]:
# Loading the Data from the source i.e. csv

# ---
#
spam_df= pd.read_csv("/content/spambase_csv.csv")



## 3. Checking the Data

In [18]:
# Determining the no. of records in our dataset
#
spam_df.shape

(4601, 58)

In [19]:
# Previewing the top of our dataset
#
spam_df.head()

   word_freq_make  word_freq_address  ...  capital_run_length_total  class
0            0.00               0.64  ...                       278      1
1            0.21               0.28  ...                      1028      1
2            0.06               0.00  ...                      2259      1
3            0.00               0.00  ...                       191      1
4            0.00               0.00  ...                       191      1

[5 rows x 58 columns]

In [20]:
# Previewing the bottom of our dataset
# 
spam_df.tail()

      word_freq_make  word_freq_address  ...  capital_run_length_total  class
4596            0.31                0.0  ...                        88      0
4597            0.00                0.0  ...                        14      0
4598            0.30                0.0  ...                       118      0
4599            0.96                0.0  ...                        78      0
4600            0.00                0.0  ...                        40      0

[5 rows x 58 columns]

In [21]:
# Checking whether each column has an appropriate datatype
#
spam_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_freq_all               4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_freq_our               4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 non-null   float64
 14  word_freq_addresses         4601 non-null   float64
 15  word_freq_free              4601 non-null   float64
 16  word_freq_business          4601 non-null   float64
 17  word_freq_email             4601 non-null   float64
 18  word_freq_you               4601 non-null   float64
 19  word_freq_credit            4601 non-null   float64
 20  word_freq_your              4601 non-null   float64
 21  word_freq_font              4601 non-null   float64
 22  word_freq_000               4601 non-null   float64
 23  word_freq_money             4601 non-null   float64
 24  word_freq_hp                4601 non-null   float64
 25  word_freq_hpl               4601 non-null   float64
 26  word_freq_george            4601 non-null   float64
 27  word_freq_650               4601 non-null   float64
 28  word_freq_lab               4601 non-null   float64
 29  word_freq_labs              4601 non-null   float64
 30  word_freq_telnet            4601 non-null   float64
 31  word_freq_857               4601 non-null   float64
 32  word_freq_data              4601 non-null   float64
 33  word_freq_415               4601 non-null   float64
 34  word_freq_85                4601 non-null   float64
 35  word_freq_technology        4601 non-null   float64
 36  word_freq_1999              4601 non-null   float64
 37  word_freq_parts             4601 non-null   float64
 38  word_freq_pm                4601 non-null   float64
 39  word_freq_direct            4601 non-null   float64
 40  word_freq_cs                4601 non-null   float64
 41  word_freq_meeting           4601 non-null   float64
 42  word_freq_original          4601 non-null   float64
 43  word_freq_project           4601 non-null   float64
 44  word_freq_re                4601 non-null   float64
 45  word_freq_edu               4601 non-null   float64
 46  word_freq_table             4601 non-null   float64
 47  word_freq_conference        4601 non-null   float64
 48  char_freq_%3B               4601 non-null   float64
 49  char_freq_%28               4601 non-null   float64
 50  char_freq_%5B               4601 non-null   float64
 51  char_freq_%21               4601 non-null   float64
 52  char_freq_%24               4601 non-null   float64
 53  char_freq_%23               4601 non-null   float64
 54  capital_run_length_average  4601 non-null   float64
 55  capital_run_length_longest  4601 non-null   int64
 56  capital_run_length_total    4601 non-null   int64
 57  class                       4601 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB

## 5. Tidying the Dataset

In [22]:
# Checking for Outliers
#
spam_df

      word_freq_make  word_freq_address  ...  capital_run_length_total  class
0               0.00               0.64  ...                       278      1
1               0.21               0.28  ...                      1028      1
2               0.06               0.00  ...                      2259      1
3               0.00               0.00  ...                       191      1
4               0.00               0.00  ...                       191      1
...              ...                ...  ...                       ...    ...
4596            0.31               0.00  ...                        88      0
4597            0.00               0.00  ...                        14      0
4598            0.30               0.00  ...                       118      0
4599            0.96               0.00  ...                        78      0
4600            0.00               0.00  ...                        40      0

[4601 rows x 58 columns]

In [23]:
# Checking for Anomalies
#
spam_df.nunique()

word_freq_make                 142
word_freq_address              171
word_freq_all                  214
word_freq_3d                    43
word_freq_our                  255
word_freq_over                 141
word_freq_remove               173
word_freq_internet             170
word_freq_order                144
word_freq_mail                 245
word_freq_receive              113
word_freq_will                 316
word_freq_people               158
word_freq_report               133
word_freq_addresses            118
word_freq_free                 253
word_freq_business             197
word_freq_email                229
word_freq_you                  575
word_freq_credit               148
word_freq_your                 401
word_freq_font                  99
word_freq_000                  164
word_freq_money                143
word_freq_hp                   395
word_freq_hpl                  281
word_freq_george               240
word_freq_650                  200
word_freq_lab                  156
word_freq_labs                 179
word_freq_telnet               128
word_freq_857                  106
word_freq_data                 184
word_freq_415                  110
word_freq_85                   177
word_freq_technology           159
word_freq_1999                 188
word_freq_parts                 53
word_freq_pm                   163
word_freq_direct               125
word_freq_cs                   108
word_freq_meeting              186
word_freq_original             136
word_freq_project              160
word_freq_re                   230
word_freq_edu                  227
word_freq_table                 38
word_freq_conference           106
char_freq_%3B                  313
char_freq_%28                  641
char_freq_%5B                  225
char_freq_%21                  964
char_freq_%24                  504
char_freq_%23                  316
capital_run_length_average    2161
capital_run_length_longest     271
capital_run_length_total       919
class                            2
dtype: int64

In [24]:
# Identifying the Missing Data
#
spam_df.isnull().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_freq_857                 0
word_freq_data                0
word_freq_415                 0
word_freq_85                  0
word_freq_technology          0
word_freq_1999                0
word_freq_parts               0
word_freq_pm                  0
word_freq_direct              0
word_freq_cs                  0
word_freq_meeting             0
word_freq_original            0
word_freq_project             0
word_freq_re                  0
word_freq_edu                 0
word_freq_table               0
word_freq_conference          0
char_freq_%3B                 0
char_freq_%28                 0
char_freq_%5B                 0
char_freq_%21                 0
char_freq_%24                 0
char_freq_%23                 0
capital_run_length_average    0
capital_run_length_longest    0
capital_run_length_total      0
class                         0
dtype: int64

In [25]:
# Checking statistical summary of the dataset
spam_df.describe(include ='all')

       word_freq_make  word_freq_address  ...  capital_run_length_total        class
count     4601.000000        4601.000000  ...               4601.000000  4601.000000
mean         0.104553           0.213015  ...                283.289285     0.394045
std          0.305358           1.290575  ...                606.347851     0.488698
min          0.000000           0.000000  ...                  1.000000     0.000000
25%          0.000000           0.000000  ...                 35.000000     0.000000
50%          0.000000           0.000000  ...                 95.000000     0.000000
75%          0.000000           0.000000  ...                266.000000     1.000000
max          4.540000          14.280000  ...              15841.000000     1.000000

[8 rows x 58 columns]

In [26]:
# More data cleaning procedures
## checking for duplicated file
#
spam_df.duplicated().sum()

391

In [27]:
#removing the duplicated data
spam_df.drop_duplicates(inplace = True)

In [28]:
#confirming if we have removed the duplicates
spam_df.duplicated().sum()

0

In [29]:
spam_df.shape

(4210, 58)

## 6.  Analysis

In [30]:
# Ploting the bivariate summaries and recording our observations
#

In [36]:
X = spam_df.iloc[:,:58].values
y = spam_df.iloc[:,-1].values

In [37]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
# Training our model
# 
clf = GaussianNB()  
model = clf.fit(X_train, y_train)

In [39]:
# Predicting our test predictors

predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

1.0

In [42]:
#model accuracy
from sklearn import metrics

print('Accuracy of Gaussian:', metrics.accuracy_score(y_test,predicted)*100)
print('\n')

Accuracy of Gaussian: 100.0

splitting 70 30

In [43]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [44]:
# Training our model
# 
clf = GaussianNB()  
model = clf.fit(X_train, y_train)

In [45]:
# Predicting our test predictors

predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.9992082343626286

In [46]:
#model accuracy
from sklearn import metrics

print('Accuracy of Gaussian:', metrics.accuracy_score(y_test,predicted)*100)
print('\n')

Accuracy of Gaussian: 99.92082343626286

splitting 60 40

In [47]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [48]:
# Training our model
# 
clf = GaussianNB()  
model = clf.fit(X_train, y_train)

In [49]:
# Predicting our test predictors

predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.997624703087886

In [50]:
#model accuracy
from sklearn import metrics

print('Accuracy of Gaussian:', metrics.accuracy_score(y_test,predicted)*100)
print('\n')

Accuracy of Gaussian: 99.7624703087886

##Multinomial Naive Bayes Classifier

In [51]:
X = spam_df.iloc[:,:58].values
y = spam_df.iloc[:,-1].values

In [52]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [53]:
# Fitting our model 


model = MultinomialNB().fit(X_train, y_train)

In [54]:
# Evaluating the Model
# Once we have put together our classifier, we can evaluate its performance in the testing set
# 
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8539192399049881

splitting 70 30

In [55]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [56]:
# Fitting our model 


model = MultinomialNB().fit(X_train, y_train)

In [57]:
# Evaluating the Model
# Once we have put together our classifier, we can evaluate its performance in the testing set
# 
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8440221694378464

splitting 60 40

In [58]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [59]:
# Fitting our model 


model = MultinomialNB().fit(X_train, y_train)

In [60]:
# Evaluating the Model
# Once we have put together our classifier, we can evaluate its performance in the testing set
# 
predicted = model.predict(X_test)
print(np.mean(predicted == y_test))

0.8426365795724465

 Bernoulli Naive Bayes Classifier

In [61]:
X = spam_df.iloc[:,:58].values
y = spam_df.iloc[:,-1].values

In [63]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [64]:
# Training our Bernoulli Naive Bayes Classifier
# 
# Creating oour Bernoulli Naive Bayes object with prior probabilities of each class
clf = BernoulliNB()

# Train model
model = clf.fit(X, y)

# model score
model.score(X, y)

0.9843230403800475

splitting 70 30

In [65]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [66]:
# Training our Bernoulli Naive Bayes Classifier
# 
# Creating oour Bernoulli Naive Bayes object with prior probabilities of each class
clf = BernoulliNB()

# Train model
model = clf.fit(X, y)

# model score
model.score(X, y)

0.9843230403800475

splitting 60 40

In [67]:
# Splitting our data into a training set and a test set
# 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [68]:
# Training our Bernoulli Naive Bayes Classifier
# 
# Creating oour Bernoulli Naive Bayes object with prior probabilities of each class
clf = BernoulliNB()

# Train model
model = clf.fit(X, y)

# model score
model.score(X, y)

0.9843230403800475

In [31]:

# guassian model perfoms better than berneuli and multinomial